// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsGreeterUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GREETER_UNSPECIFIED.String() && e.Code == 500
}

func ErrorGreeterUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_GREETER_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 500
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsCodeInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CodeInvalid.String() && e.Code == 501
}

func ErrorCodeInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(501, ErrorReason_CodeInvalid.String(), fmt.Sprintf(format, args...))
}

func IsQuestionNull(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_QuestionNull.String() && e.Code == 501
}

func ErrorQuestionNull(format string, args ...interface{}) *errors.Error {
	return errors.New(501, ErrorReason_QuestionNull.String(), fmt.Sprintf(format, args...))
}
